apiVersion: v1
kind: Service
metadata:
  name: sre-grafana
spec:
  selector:
    app: sre-grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-grafana
  template:
    metadata:
      labels:
        app: sre-grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000