apiVersion: v1
kind: Service
metadata:
  name: sre-postgres 
spec:
  selector:
    app: sre-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-postgres
  template:
    metadata:
      labels:
        app: sre-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "telemetry"
        volumeMounts:
        - name: init-script-volume
          mountPath: /docker-entrypoint-initdb.d 
      volumes:
      - name: init-script-volume
        configMap:
          name: postgres-init-config 